### ISSUE TITLE
sry

### ISSUE THREAD

**Issue by sebtout** [sak96/todo.conky#4]
sorry I thought you spoke French 
![1](https://user-images.githubusercontent.com/82059429/220333500-b00bb51a-d8a8-4fc6-ad57-8764189d1058.png)
![2](https://user-images.githubusercontent.com/82059429/220333551-bde3230b-af61-480c-b673-030272aafbb3.png)

am I doing something wrong

**Comment by sebtout** [comment]
its ok I did not say anything

**Comment by sebtout** [comment]
it's just the manipulation of ## and [ ], [ . ], [x] that I didn't quite understand

**Comment by sak96** [comment]
did you figure it out ?
the sample todo.md has different variation that can be tried out.
